version: '3.4'

services:
  pocTestContainer.db:
    container_name: pocTestContainer
    hostname: pocTestContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
    ports:
      - 1433:1433   

networks:
  default:
    name: poctestecontainer